### ISSUE TITLE
Self hosting - No Chat id

### ISSUE THREAD

**Issue by soapoperator** [idoco/intergram#13]
Hello,

I try to host this good app.
As i am not very familiar with node.js, i think i succeed to go to step 4.

On the webhook, i get :
`{"ok":true,"result":true,"description":"Webhook was set"}`

Unfortunately when i open my bot with `/start`, no chat id was delivred.
So i can't embed the snippet...

Is the webhook well related to the bot configuration? Is there a delay with initialisation?
Any idea?

Thank you in advance for the help.
jb

**Comment by idoco** [comment]
Hi @soapoperator 
Do you see something in the server logs? If the server received your start message and tried to answer it you should see something like `/start chatId 123`.

If you see this message in the log but not in the chat, it is most likely that you didn't set the .env variable `TELEGRAM_TOKEN` properly.

If you don't see this log message, try to send a POST message directly to the server `/hook` from any REST client just to see if it works. You can use this json body to test it -
```json
{
   "message":{
      "chat":{
         "id":123,
         "first_name":"test"
      },
      "text":"/start"
   }
}
```

**Comment by soapoperator** [comment]
Thank you @idoco for your quick answer.
I don't see anything in the log.

I try to send a POST with the your json to test to `https://my.adress.com/hook`. 
And i get an 404:
```w
<h2>Error 404</h2>
<address>
  <a href="/">my.adress.com</a><br />
  <span>Wed Mar 15 21:42:42 2017<br />
  Apache/2.2.31 (Unix) DAV/2 mod_ssl/2.2.31 OpenSSL/1.0.2j</span>
</address>
```
I guess my app installation is wrong?

**Comment by idoco** [comment]
Hi, yeah, it might be that you didn't install it right.
Did you run `npm install`  and `npm start` in the cloned folder? 

The default server port is 3000,  can you try sending the POST to `https://my.adress.com:3000/hook` (Or did you map port 3000 to 80 and expect this to work?)

**Comment by soapoperator** [comment]
Hi,
It seems to be better now. I get not error and a beautiful :
``` 
listening on port:3000
```

Unfortunately when i test POST request to `https://my.adress.com:3000/hook`, i still get an error:
```
Error: socket hang up
```
Maybe an error with the server. I will try to start with _forever_ this week-end.

Thank you for the help.

**Comment by soapoperator** [comment]
Hi,
Sorry for the delay.
Start the app with _forever_ doesn't change anything.
I get this error:
`Error: socket hang up`
With my test request:
```
{
   "message":{
      "chat":{
         "id":123,
         "first_name":"test"
      },
      "text":"/start"
   }
}
```
But as i didn't get the chat.id, isn't it normal?

**Comment by idoco** [comment]
Yes, I didn't expect forever to fix the issue.
Did you also try to use `http` instead of `https`?

If you want, you can contact me privately by email `ido.mapchat at gmail.com` or Telegram `@idoco` and I can connect to your machine and try to debug it

**Comment by soapoperator** [comment]
idoco,

Thank you for the reply.
With http, i get an `200 OK` response without anything else.
So i try to re /start the bot. No chat id, nothing.

I will send you a message at telegram.

**Comment by joseh55** [comment]
Hi !!!! please i need help ...
i make a git clone https://github.com/idoco/intergram.git
later... in the folder intergram i make: 
[root@tte intergram]# npm install
npm WARN package.json intergram@0.0.1 No repository field.
npm WARN cannot run in wd intergram@0.0.1 npm run build (wd=/var/www/html/a2billing/customer/intergram)
[root@tte intergram]#

======================================================
LATER:
[root@tte intergram]# npm start

> intergram@0.0.1 start /var/www/html/a2billing/customer/intergram
> node server.js


/var/www/html/a2billing/customer/intergram/server.js:30
            let replyText = reply.text || "";
                ^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
npm ERR! weird error 8
npm ERR! not ok code 0

always i have errors with npm

Can you help me??

**Comment by amudy17** [comment]
Hello,

i have try to host in on heroku, 

its works good but cannot open chatid, and did install normal on heroku at point of issue #50. 
altough i have did to webhook but not shown chatid.

`{"ok":true,"result":true,"description":"Webhook is already set"}`

please advise , how to show chatid in bot telegram ?
