### ISSUE TITLE
Support Telegram channels

### ISSUE THREAD

**Issue by idoco** [idoco/intergram#14]
Or at least respond with a proper message stating that channels are not supported.
Right now an exception is logged and no response is sent.

```
  hook error TypeError: Cannot read property 'chat' of undefined 
      at /app/server.js:17:31 
      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5) 
      at next (/app/node_modules/express/lib/router/route.js:100:13) 
      at Route.dispatch (/app/node_modules/express/lib/router/route.js:81:3) 
      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5) 
      at /app/node_modules/express/lib/router/index.js:235:24 
      at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:313:12) 
      at /app/node_modules/express/lib/router/index.js:229:12 
      at Function.match_layer (/app/node_modules/express/lib/router/index.js:296:3) 
      at next (/app/node_modules/express/lib/router/index.js:190:10) { update_id: 77942168, 
    edited_channel_post:  
     { message_id: 900, 
       chat:  
        { id: -1001075661967, 
          title: 'Title', 
          username: 'username', 
          type: 'channel' }, 
       date: 1489989251, 
       edit_date: 1489995912, 
       text: '@ChannelName\nThis is a channel message', 
       entities: [ [Object] ] } } 
```

A nice issue for a first PR 😄

**Comment by oregonisaac** [comment]
Is this project supposed to work in Channels or in Groups?  I'm thinking it's setup only for individual users?  I can't get it to work in a small Group chat either.

**Comment by oregonisaac** [comment]
Actually, I just figured it out.  I had two issues: to receive messages I needed to add the "-" character before my Instagram ID in the javascript on the web page...and to send messages I needed to use a directly "right click reply" in telegram
