### ISSUE TITLE
Install InterGram

### ISSUE THREAD

**Issue by Ehsan-Np** [idoco/intergram#24]
Hi!
Can You Install intergram in my self host and self bot?

**Comment by idoco** [comment]
Yes, there is a short guide in the [readme file](https://github.com/idoco/intergram#deploy-your-own-intergram-instance-self-hosting)

It's easiest to deploy it to Heroku (because this is what I do), but you can also deploy it to your own server (You will need to setup an SSL certificate for it, set few environment variables and maybe to change few lines in server.js)

**Comment by sah-anshu** [comment]
Hi I am unable to install. i guess there is some problem in code/node version. . 

whatsapi@s002:~/intergram$ node server.js 

/home/whatsapi/intergram/server.js:30
            let replyText = reply.text || "";
                ^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
whatsapi@s002:~/intergram$ node -v
v0.10.29
whatsapi@s002:~/intergram$ npm -v
1.4.21
whatsapi@s002:~/intergram$

**Comment by xenu256** [comment]
Installation works with 
- node v8.6.0 
- npm 5.4.2
on mys side.

**Comment by idoco** [comment]
Hey @sah-anshu , 'let' support was added in Node.js 4.x. are you using an older version?

**Comment by sah-anshu** [comment]
Thanks. I have achieved the things running by upgrading node and npm but i don't understand how can i attach hook to telegram, can't see any option like that. 

Secondly. I see websocket error. pl find the screenshot. 
![screen shot 2017-12-07 at 1 47 32 pm](https://user-images.githubusercontent.com/9985291/33705724-6184b84a-db57-11e7-8aaa-aa8427d8df3e.png)

-
Anshu

**Comment by xenu256** [comment]
You should follow readme instructions: "Deploy your own Intergram instance (Self Hosting)".

**Comment by sah-anshu** [comment]
I can see the 3rd point there:

- Point the bot webhook to your bot server by making a GET request to the following url https://api.telegram.org/bot<TOKEN>/setWebhook?url=<Server url>/hook (Don't forget to replace with your token and server ur

But how to point that webhook. ie my question and i am stuck there.

Anshu

**Comment by xenu256** [comment]
Probably you need to configure and run chat server (server.js). I ran it under  Nginx and subdomain and pointed that subdomain to Telegram API url.

**Comment by sah-anshu** [comment]
Ok. pl explain more. 
right now i am serving on the url http://whatsapi.in and it works . but next is configure webhook url in telegram bot. I want to know how to configure that.

Anshu

**Comment by xenu256** [comment]
You should follow all instructions. As I see, your page runs code with default chat ID. Start the Telegram bot and if your server is running and hook is enabled on Telegram side (via url) it will, the bot will show your own chat ID. If not, then your server isn't running or you didn't set a hook through url.

**Comment by Hg347** [comment]
Hi, I read your short install instructions. Could you elaborate more what exactly of the repo I should put in what folder hierarchy on my web server?

**Comment by idoco** [comment]
Hi @Hg347, this means you should go to the cloned folder and run `npm install` from the terminal.
(this is assuming you have node.js/npm install on your machine)

**Comment by xunorus** [comment]
GUYS CHECK HERE TO FIND OUT HOW TO SET THE TELEGRAM BOT!
https://medium.com/@xabaras/setting-your-telegram-bot-webhook-the-easy-way-c7577b2d6f72
